# Analiza i Bazy Danych

***Notatki***   
    df.to_csv("dem_score.csv")  
    df.loc[id==[mx000]] # tak sie odwolujemy do df  
    wieksze np. od jakiejs temperatury, nizej operacja na ciagow bitow &  
    df.loc[(id=='') & (d1>10)]  

10 minutes to pandas sobie obczaic
     pd.read_excel('dem_score.xlsx', index_col=0)

In [1]:
import pandas as pd
# df - data frame

df = pd.read_csv("Datasets/tb.csv")

df

,iso2,year,new_sp,new_sp_m04,new_sp_m514,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,...,new_sp_f04,new_sp_f514,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sp_fu
0,AD,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AD,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AD,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AD,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AD,1993,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5764,ZW,2004,14581.0,NaN,NaN,187.0,833.0,2908.0,2298.0,1056.0,...,NaN,NaN,225.0,1140.0,2858.0,1565.0,622.0,214.0,111.0,NaN
5765,ZW,2005,13155.0,NaN,NaN,210.0,837.0,2264.0,1855.0,762.0,...,NaN,NaN,269.0,1136.0,2242.0,1255.0,578.0,193.0,603.0,NaN
5766,ZW,2006,12718.0,NaN,NaN,215.0,736.0,2391.0,1939.0,896.0,...,NaN,NaN,237.0,1020.0,2424.0,1355.0,632.0,230.0,96.0,NaN
5767,ZW,2007,10583.0,6.0,132.0,138.0,500.0,3693.0,0.0,716.0,...,7.0,178.0,185.0,739.0,3311.0,0.0,553.0,213.0,90.0,NaN
5768,ZW,2008,9830.0,NaN,NaN,127.0,614.0,0.0,3316.0,704.0,...,NaN,NaN,145.0,840.0,0.0,2890.0,467.0,174.0,105.0,0.0

In [3]:
# Sposob na wyrzucenie wartosci "NaN"
df1 = df.dropna()

In [7]:
# Zrzut zbędnych zer, których było sporo
x = df1.copy()
for i in df:
    if i!="iso2":
        x=x[x[i]>0]
x

,iso2,year,new_sp,new_sp_m04,new_sp_m514,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,...,new_sp_f04,new_sp_f514,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sp_fu
244,AR,2008,4758.0,11.0,58.0,69.0,633.0,611.0,390.0,416.0,...,5.0,61.0,66.0,536.0,506.0,252.0,221.0,157.0,204.0,8.0
1620,ES,2005,2511.0,6.0,7.0,13.0,166.0,394.0,367.0,230.0,...,6.0,4.0,10.0,142.0,252.0,151.0,63.0,24.0,108.0,2.0
1621,ES,2006,2006.0,12.0,6.0,18.0,142.0,332.0,311.0,232.0,...,8.0,9.0,17.0,122.0,264.0,137.0,48.0,19.0,77.0,1.0
1622,ES,2007,2317.0,4.0,6.0,10.0,184.0,375.0,379.0,257.0,...,8.0,4.0,12.0,164.0,291.0,136.0,63.0,23.0,93.0,2.0
1822,GB,2007,1639.0,2.0,11.0,13.0,183.0,286.0,223.0,169.0,...,1.0,19.0,20.0,145.0,222.0,91.0,58.0,45.0,138.0,2.0
2478,IT,2006,1377.0,6.0,1.0,7.0,113.0,201.0,197.0,105.0,...,3.0,6.0,9.0,88.0,165.0,82.0,48.0,16.0,88.0,10.0
2480,IT,2008,938.0,1.0,12.0,13.0,78.0,148.0,137.0,72.0,...,3.0,7.0,10.0,65.0,106.0,56.0,24.0,21.0,56.0,1.0
4302,PT,2005,1302.0,3.0,2.0,5.0,85.0,227.0,284.0,181.0,...,3.0,4.0,7.0,67.0,109.0,66.0,29.0,11.0,42.0,1.0
4303,PT,2006,1300.0,4.0,3.0,7.0,80.0,211.0,259.0,190.0,...,1.0,3.0,4.0,56.0,107.0,85.0,33.0,22.0,41.0,1.0
4415,RO,2005,10801.0,10.0,26.0,36.0,752.0,1511.0,1786.0,1999.0,...,8.0,47.0,55.0,758.0,780.0,493.0,374.0,219.0,442.0,2.0

In [8]:
# #zmiana nazw kolumn
# earthquake_data_renamed_columns = earthquake_data.rename(columns=
#                 {'In general, how worried are you about earthquakes?': "worried about earthquakes",
#                 'How worried are you about the Big One, a massive, catastrophic earthquake?': "worried about the Big One",
#                 'Do you think the "Big One" will occur in your lifetime?': "Big One during lifetime probability", 
#                 'Have you ever experienced an earthquake?': "experienced of earthquake",
#                 'Have you or anyone in your household taken any precautions for an earthquake (packed an earthquake survival kit, prepared an evacuation plan, etc.)?': "earthquake prevention",
#                 'How familiar are you with the San Andreas Fault line?': "knowledge about San Andreas Fault line",
#                 'How familiar are you with the Yellowstone Supervolcano?': "knowledge about Yellowstone Supervolcano",
#                 'Age': "age",
#                 'What is your gender?': "gender",
#                 'How much total combined money did all members of your HOUSEHOLD earn last year?': "household earnings",
#                 'US Region': "region"})
# earthquake_data_renamed_columns